Obaltazar2k/SCPP

- SCPP/App.config
- SCPP/App.xaml
- SCPP/AsignarProyectoEstudiante.xaml
- SCPP/AsignarProyectoEstudiante.xaml.cs
- SCPP/IniciarSesion.xaml
- SCPP/IniciarSesion.xaml.cs
- SCPP/MainWindow.xaml
- SCPP/MainWindow.xaml.cs
- SCPP/SCPP.csproj
- SCPP/packages.config
-Se agrega la funcionalidad del CU01 Asignar proyecto estudiante más los cambios requeridos en los diferentes archivos.
> Funcionalidad de CU01 Asignar Proyecto a Estudiante

- SCPP/App.config
- SCPP/IniciarSesion.xaml
- SCPP/IniciarSesion.xaml.cs
- SCPP/MenuCoordinador.xaml
- SCPP/MenuCoordinador.xaml.cs
- SCPP/MenuEstudiante.xaml
- SCPP/MenuEstudiante.xaml.cs
- SCPP/MenuProfesor.xaml
- SCPP/MenuProfesor.xaml.cs
- SCPP/SCPP.csproj
Login terminado con navegación hacia el menu principal de cada usuario
> BR-IniciarSesion

- SCPP/App.config
- SCPP/AsignarProfesorGrupo.xaml
- SCPP/AsignarProfesorGrupo.xaml.cs
- SCPP/AsignarProyectoEstudiante.xaml.cs
- SCPP/Coordinador.cs
- SCPP/IniciarSesion.xaml
- SCPP/IniciarSesion.xaml.cs
- SCPP/MenuCoordinador.xaml
- SCPP/MenuCoordinador.xaml.cs
- SCPP/Profesor.cs
- SCPP/SCPP.csproj
- SCPP/SCPPModel.edmx
- SCPP/SCPPModel.edmx.diagram
- SCPP/Utilities/Period.cs
Funcionalidad asignar profesor a grupo completa, también se actualizo la base de datos con los nuevo requerimientos.
> Br asignar profesor a grupo

- SCPP/AsignarProyectoEstudiante.xaml.cs
- SCPP/MenuCoordinador.xaml
- SCPP/MenuCoordinador.xaml.cs
- SCPP/RegistrarEstudiante.xaml.cs
- SCPP/RegistrarProyecto.xaml
- SCPP/RegistrarProyecto.xaml.cs
- SCPP/SCPP.csproj
- Se agrega la funcionalidad del CU09 Registrar estudiante más los cambios requeridos en los diferentes archivos.
> Funcionalidad CU11 Registrar proyecto

- SCPP/App.config
- SCPP/RegistrarOrganizacion.xaml
- SCPP/RegistrarOrganizacion.xaml.cs
- SCPP/SCPP.csproj
Se creo CU Registrar Organización :)
> Br registrar organizacion

- SCPP/App.config
- SCPP/RegistrarProfesor.xaml
- SCPP/RegistrarProfesor.xaml.cs
- SCPP/SCPP.csproj
Actualización del caso de uso Registrar Profesor
> Caso de uso Registrar Profesor

- SCPP/App.config
- SCPP/DesasignarProfesorGrupo.xaml
- SCPP/DesasignarProfesorGrupo.xaml.cs
- SCPP/IniciarSesion.xaml.cs
- SCPP/MainWindow.xaml
- SCPP/MenuCoordinador.xaml
- SCPP/MenuCoordinador.xaml.cs
- SCPP/SCPP.csproj
- SCPP/SCPPModel.edmx.diagram
Realización de CU Desasignar profesor a grupo
> Br desasignar profesor a grupo

- SCPP/App.config
- SCPP/SCPP.csproj
- SCPP/ValidarInscripcion.xaml
- SCPP/ValidarInscripcion.xaml.cs
Funcionalidad del caso de uso Validar Preinscripción
> Caso de uso Validar Preinscripción

- SCPP/RegistrarInscripcion.xaml
- SCPP/RegistrarInscripcion.xaml.cs
- SCPP/SCPP.csproj
Funcionalidad del caso de uso Registrar Inscripción
> CU Registrar inscripcion

- SCPP/AsociarEstudianteGrupo.xaml
- SCPP/AsociarEstudianteGrupo.xaml.cs
- SCPP/SCPP.csproj
Se termino CU AsociarEstudianteGrupo :)
> Br asociar estudiante grupo

- SCPP/IniciarSesion.xaml.cs
- SCPP/MenuCoordinador.xaml
- SCPP/MenuCoordinador.xaml.cs
- SCPP/RegistrarProfesor.xaml
- SCPP/RegistrarProfesor.xaml.cs
Se agrega la estandarización de mis CU´s junto con los respectivos botones de los Menus
> Estandarización Aldo

- SCPP/EscogerProyecto.xaml
- SCPP/EscogerProyecto.xaml.cs
- SCPP/MenuEstudiante.xaml
- SCPP/MenuEstudiante.xaml.cs
- SCPP/SCPP.csproj
Se termino CU y se agrego navegabilidad entre menú estudiante y escoger proyecto
> Br escoger proyecto

- SCPP/App.xaml
- SCPP/View/AsociarEstudianteGrupo.xaml.cs
- SCPP/View/MenuProfesor.xaml
- SCPP/View/MenuProfesor.xaml.cs
Se creo el botón de navegabilidad a AsociarEstudianteGrupo en MenuProfesor
> Se agrego botón en menú profesor

- SCPP/App.config
- SCPP/App.xaml
- SCPP/View/AsignarProfesorGrupo.xaml.cs
- SCPP/View/DesasignarProfesorGrupo.xaml.cs
- SCPP/View/IniciarSesion.xaml.cs
Excepciones en Login, Asignar y Desasignar profesor a grupo
> Excepción de conexión con la BD

- SCPP/View/RegistrarInscripcion.xaml.cs
- SCPP/View/RegistrarProfesor.xaml.cs
- SCPP/View/ValidarInscripcion.xaml.cs
Excepciones de Registrar Profesor, Registrar Inscripción y Validar Inscripción
> Manejo Excepción base de datos

- SCPP.sln
- SCPP/SCPP.csproj
- SCPP/packages.config
- UnitTest/App.config
- UnitTest/DataAccessTest/ProfesorTest.cs
- UnitTest/DataAccessTest/StudentTest.cs
- UnitTest/Properties/AssemblyInfo.cs
- UnitTest/UnitTest.csproj
- UnitTest/packages.config
Pruebas unitarias de Estudiante y Profesor
> Br unit test

- UnitTest/DataAccessTest/OrganizationTest.cs
- UnitTest/DataAccessTest/ProyectTest.cs
- UnitTest/UnitTest.csproj
Pruebas unitarias de Organización y Proyecto
> Pruebas Unitarias Aldo

- UnitTest/DataAccessTest/InscriptionTest.cs
- UnitTest/UnitTest.csproj
Se crearon las pruebas de inscripción
> Se crearon pruebas de Inscripción

- UnitTest/DataAccessTest/ExpedienteTest.cs
- UnitTest/UnitTest.csproj
Se terminaron las pruebas unitarias de expediente
> Br unit test pale

- SCPP/App.config
- UnitTest/App.config
- UnitTest/DataAccessTest/ExpedienteTest.cs
- UnitTest/DataAccessTest/GroupTest.cs
- UnitTest/DataAccessTest/InscriptionTest.cs
- UnitTest/DataAccessTest/OrganizationTest.cs
- UnitTest/DataAccessTest/ProfesorTest.cs
- UnitTest/DataAccessTest/ProyectSelectionTest.cs
- UnitTest/DataAccessTest/ProyectTest.cs
- UnitTest/DataAccessTest/StudentTest.cs
- UnitTest/UnitTest.csproj
Corrección general de pruebas unitarias de Data Access
> Pruebas unitarias

- SCPP/View/EscogerProyecto.xaml.cs
- SCPP/View/IniciarSesion.xaml
También se modificaron algunas cosas de la interfaz de iniciar sesión.
> Se actualizó el CU Escoger proyecto

- SCPP/DataAcces/Estudiante.cs
- SCPP/DataAcces/Organización.cs
- SCPP/DataAcces/Proyecto.cs
- SCPP/DataAcces/Responsableproyecto.cs
- SCPP/DataAcces/SCPPModel.Context.cs
- SCPP/DataAcces/SCPPModel.Designer.cs
- SCPP/DataAcces/SCPPModel.edmx
- SCPP/DataAcces/SCPPModel.edmx.diagram
- SCPP/SCPP.csproj
- SCPP/View/RegistrarEstudiante.xaml
- SCPP/View/RegistrarEstudiante.xaml.cs
- SCPP/View/RegistrarInscripcion.xaml.cs
- SCPP/View/RegistrarOrganizacion.xaml
- SCPP/View/RegistrarOrganizacion.xaml.cs
- SCPP/View/RegistrarProfesor.xaml.cs
- SCPP/View/RegistrarProyecto.xaml.cs
- Actualización de BD
- Corrección mínima de algunas pantallas
- Actualización de creación de entidades en los registrar
> Cambios en el modelo de base de datos y correcciones mínimas

- SCPP/DataAcces/Estudiante.cs
- SCPP/DataAcces/Organización.cs
- SCPP/DataAcces/Profesor.cs
- SCPP/DataAcces/Proyecto.cs
- SCPP/DataAcces/Responsableproyecto.cs
- SCPP/DataAcces/SCPPModel.edmx
- SCPP/DataAcces/SCPPModel.edmx.diagram
- SCPP/View/AsignarProyectoEstudiante.xaml.cs
- SCPP/View/RegistrarEstudiante.xaml.cs
- SCPP/View/RegistrarOrganizacion.xaml
- SCPP/View/RegistrarOrganizacion.xaml.cs
- SCPP/View/RegistrarProyecto.xaml
- SCPP/View/RegistrarProyecto.xaml.cs
De casos de uso
- Registrar proyecto
- Registrar organización
- Asignar proyecto estudiante
Cambio en el modelo de BD
> Correcciones generales

- SCPP/App.config
- SCPP/SCPP.csproj
- SCPP/View/AsignarProfesorGrupo.xaml.cs
- SCPP/View/ConsultarEstudiantes.xaml
- SCPP/View/ConsultarEstudiantes.xaml.cs
- SCPP/View/MenuCoordinador.xaml
- SCPP/View/MenuCoordinador.xaml.cs
- SCPP/View/MenuProfesor.xaml
- SCPP/View/MenuProfesor.xaml.cs
- SCPP/View/RegistrarEstudiante.xaml.cs
- SCPP/View/RegistrarProfesor.xaml.cs
- SCPP/packages.config
- Se agrego Consultar estudiantes.
- Se modificaron pantallas.
- Se modificaron errores menores en otros cs.
> Estandarización de Consultar

- SCPP/SCPP.csproj
- SCPP/Utilities/FieldsVerificator.cs
- SCPP/View/AsignarProfesorGrupo.xaml
- SCPP/View/AsignarProyectoEstudiante.xaml
- SCPP/View/AsociarEstudianteGrupo.xaml
- SCPP/View/ConsultarEstudiantes.xaml
- SCPP/View/ConsultarEstudiantes.xaml.cs
- SCPP/View/DesasignarProfesorGrupo.xaml
- SCPP/View/EscogerProyecto.xaml
- SCPP/View/GestionarEstudiante.xaml
- SCPP/View/GestionarEstudiante.xaml.cs
- SCPP/View/RegistrarEstudiante.xaml.cs
- SCPP/View/RegistrarInscripcion.xaml.cs
- SCPP/View/ValidarInscripcion.xaml
- Se agregó Gestionar estudiante.
- Se agregó FieldsVerificator a las utilidades del proyecto, y se modificó Registrar estudiante y Registrar inscripción para que emplearan de él.
- Se modificaron pantallas, específicamente tablas.
- Se modificaron errores menores en otros CS.
> Estandarización de gestionar

- SCPP/App.config
- SCPP/App.xaml
- SCPP/App.xaml.cs
- SCPP/SCPP.csproj
- SCPP/Utilities/Sesion.cs
- SCPP/View/GestionarEstudiante.xaml.cs
- SCPP/View/GestionarExpediente.xaml
- SCPP/View/GestionarExpediente.xaml.cs
- SCPP/View/IniciarSesion.xaml.cs
- SCPP/View/MainWindow.xaml
- SCPP/packages.config
- Se agregó la funcionalidad parcial de gestionar expediente (Queda pendiente la parte de subir reporte).
- Se agregó Tipo de sesión a la utilería sesión
- Se cambio la paleta de colores en el login para los ComboBoxes (Queda a sugerencia)
- Se agregó un paquete NuGet
- Correcciones menores
> Br gestionar expediente

- SCPP/SCPP.csproj
- SCPP/View/ConsultarGrupos.xaml
- SCPP/View/ConsultarGrupos.xaml.cs
- SCPP/View/GestionarGrupo.xaml
- SCPP/View/GestionarGrupo.xaml.cs
- SCPP/View/MenuProfesor.xaml
- SCPP/View/MenuProfesor.xaml.cs
Casos de uso Consultar y Gestionar grupo
> Casos de uso Consultar y gestionar grupo

- SCPP/SCPP.csproj
- SCPP/View/EntregarReporte.xaml
- SCPP/View/EntregarReporte.xaml.cs
- SCPP/View/GestionarExpediente.xaml
- SCPP/View/GestionarExpediente.xaml.cs
Se agrega la funcionalidad entregar reporte
> CU12 Entregar reporte

- SCPP/View/ConsultarGrupos.xaml
- SCPP/View/ConsultarGrupos.xaml.cs
- SCPP/View/GestionarGrupo.xaml
- SCPP/View/GestionarGrupo.xaml.cs
- SCPP/View/MenuCoordinadorGroups.xaml.cs
Se dividen funcionalidades entre coordinador y profesor para grupo
> Actualización de grupo

- SCPP/App.config
- SCPP/SCPP.csproj
- SCPP/Utilities/FieldsVerificator.cs
- SCPP/View/AsociarEstudianteGrupo.xaml.cs
- SCPP/View/ConsultarGrupos.xaml
- SCPP/View/GestionarGrupo.xaml.cs
- SCPP/View/MenuCoordinadorGroups.xaml
- SCPP/View/MenuCoordinadorGroups.xaml.cs
- SCPP/View/RegistrarGrupo.xaml
- SCPP/View/RegistrarGrupo.xaml.cs
- SCPP/View/RegistrarProfesor.xaml.cs
- SCPP/View/RegistrarProyecto.xaml
- Cu registrar grupos
- Corrección de cupo en CU asociar grupo a estudiante
> Br registrar grupo

- SCPP/View/ConsultarGrupos.xaml.cs
- SCPP/View/GestionarGrupo.xaml.cs
- SCPP/View/GestionarResposable.xaml.cs
- SCPP/View/RegistrarInscripcion.xaml.cs
- SCPP/View/RegistrarProfesor.xaml.cs
- SCPP/View/RegistrarResposable.xaml.cs
- SCPP/View/ValidarInscripcion.xaml.cs
Se actualizan las excepciones con las clase Restarter
> Actualización de Excepciones

- SCPP/App.config
- SCPP/App.xaml
- SCPP/SCPP.csproj
- SCPP/Utilities/Period.cs
- SCPP/View/AsignarProfesorGrupo.xaml.cs
- SCPP/View/AsignarProyectoEstudiante.xaml.cs
- SCPP/View/ConsultarProfesores.xaml.cs
- SCPP/View/DesasignarProfesorGrupo.xaml.cs
- SCPP/View/EntregarReporte.xaml.cs
- SCPP/View/GenerarOficioAsignacion.xaml
- SCPP/View/GenerarOficioAsignacion.xaml.cs
- SCPP/View/GestionarProfesor.xaml.cs
- SCPP/View/IniciarSesion.xaml.cs
- SCPP/View/MenuCoordinadorOrganization.xaml.cs
- SCPP/View/MenuCoordinadorStudent.xaml
- SCPP/View/MenuCoordinadorStudent.xaml.cs
- SCPP/View/RegistrarGrupo.xaml.cs
Se creo la función para generar el oficio de asignación y se agregaron algunas excepciones faltantes de la conexión a la base de datos.
> Br generar oficio asignación

- SCPP/App.config
- SCPP/DataAcces/Reporte.cs
- SCPP/DataAcces/SCPPModel.Designer.cs
- SCPP/DataAcces/SCPPModel.edmx
- SCPP/SCPP.csproj
- SCPP/View/CalificarReporte.xaml
- SCPP/View/CalificarReporte.xaml.cs
- SCPP/View/ConsultarEstudiantes.xaml
- SCPP/View/ConsultarEstudiantes.xaml.cs
- SCPP/View/VerReportes.xaml
- SCPP/View/VerReportes.xaml.cs
Se agregó ventana de Ver reportes y Calificar reportes, además se modifico consultar estudiantes para que los profesores tengan la opción de Ver los reportes de un estudiante. Se modifico el modelo, se agregaron dos atributos a reporte, calificación y comentario
> Se agregaron las pantallas para el CU-Calificar reportes

- SCPP/Utilities/FieldsVerificator.cs
- SCPP/View/CalificarReporte.xaml
- SCPP/View/CalificarReporte.xaml.cs
- SCPP/View/RegistrarResposable.xaml
- SCPP/View/RegistrarResposable.xaml.cs
- SCPP/View/VerReportes.xaml
- SCPP/View/VerReportes.xaml.cs
Se agrega la funcionalidad de calificar reporte, y la corrección de Registrar resposable
> Funcionalidad Calificar reporte

- SCPP/View/CalificarReporte.xaml
- SCPP/View/CalificarReporte.xaml.cs
- SCPP/View/ConsultarEstudiantes.xaml
- SCPP/View/ConsultarEstudiantes.xaml.cs
- SCPP/View/VerReportes.xaml.cs
Se cambio el CU para que la funcionalidad sea en una sola pantalla al ser un caso de uso corto
> Actualización Calificar reporte

- SCPP/App.xaml
- SCPP/View/AsignarProfesorGrupo.xaml.cs
- SCPP/View/CalificarReporte.xaml
- SCPP/View/CalificarReporte.xaml.cs
- SCPP/View/DesasignarProfesorGrupo.xaml.cs
- SCPP/View/DesasignarProyectoEstudiante.xaml.cs
- SCPP/View/GenerarOficioAsignacion.xaml
- SCPP/View/GestionarEstudiante.xaml.cs
- SCPP/View/GestionarExpediente.xaml
- SCPP/View/GestionarExpediente.xaml.cs
- SCPP/View/MenuEstudiante.xaml
- SCPP/View/MenuEstudiante.xaml.cs
- SCPP/View/RegistrarEstudiante.xaml.cs
- SCPP/View/RegistrarOrganizacion.xaml.cs
- SCPP/View/RegistrarProfesor.xaml.cs
- SCPP/View/RegistrarResposable.xaml
Ahora el estudiante puede ver su calificación y comentario desde el expediente.
Se corrigieron problemas de validación
> Se modifico calificar reporte
